In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv(r'../../Datasets/titanic.csv')
df

df = df[['Survived', 'Age', 'Fare', 'Pclass']]
df

     Survived   Age      Fare  Pclass
0           0  34.5    7.8292       3
1           1  47.0    7.0000       3
2           0  62.0    9.6875       2
3           0  27.0    8.6625       3
4           1  22.0   12.2875       3
..        ...   ...       ...     ...
413         0   NaN    8.0500       3
414         1  39.0  108.9000       1
415         0  38.5    7.2500       3
416         0   NaN    8.0500       3
417         0   NaN   22.3583       3

[418 rows x 4 columns]

In [3]:
df.isnull().mean()

Survived    0.000000
Age         0.205742
Fare        0.002392
Pclass      0.000000
dtype: float64

In [4]:
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())
df.isnull().mean()

Survived    0.000000
Age         0.205742
Fare        0.000000
Pclass      0.000000
dtype: float64

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2, random_state=2)

In [6]:
KNNimputer = KNNImputer(n_neighbors=3)
Simpleimputer = SimpleImputer()

X_train_KNN_trf = KNNimputer.fit_transform(X_train)
X_test_KNN_trf = KNNimputer.transform(X_test)

X_train_simple_trf = Simpleimputer.fit_transform(X_train)
X_test_simple_trf = Simpleimputer.transform(X_test)

In [7]:
# pd.DataFrame(X_train_trf, columns=X_train.columns).isnull().mean()
pd.DataFrame(X_train_KNN_trf, columns=X_train.columns)

           Age     Fare  Pclass
0    23.000000   8.6625     3.0
1     2.000000  20.2125     3.0
2    39.000000  13.4167     3.0
3    21.000000   7.2250     3.0
4    31.000000  21.0000     2.0
..         ...      ...     ...
329  29.000000   7.8542     3.0
330  28.333333  31.6833     1.0
331  29.000000   7.9250     3.0
332  24.000000  27.7208     2.0
333  34.833333  27.7208     1.0

[334 rows x 3 columns]

In [8]:
lr1 = LogisticRegression()
lr2 = LogisticRegression()

lr1.fit(X_train_KNN_trf, y_train)
lr2.fit(X_train_simple_trf, y_train)

y_pred_KNN = lr1.predict(X_test_KNN_trf)
y_pred_simple = lr2.predict(X_test_simple_trf)

print('Accuracy score with KNN: ', accuracy_score(y_pred_KNN, y_test))
print('Accuracy score with simple: ', accuracy_score(y_pred_simple, y_test))

Accuracy score with KNN:  0.6666666666666666
Accuracy score with simple:  0.6428571428571429

In [ ]:
for i in range(1, 11):
    imputer = KNNImputer(n_neighbors=i)
    X_train_KNN_trf = imputer.fit_transform(X_train)
    X_test_KNN_trf = imputer.transform(X_test)

    lr = LogisticRegression()
    lr.fit(X_train_KNN_trf, y_train)
    y_pred = lr.predict(X_test_KNN_trf)

    print(f'Accuracy score with {i} neighbors: ', accuracy_score(y_pred, y_test))

Accuracy score with 1 neighbors:  0.6428571428571429
Accuracy score with 2 neighbors:  0.6666666666666666
Accuracy score with 3 neighbors:  0.6666666666666666
Accuracy score with 4 neighbors:  0.6547619047619048
Accuracy score with 5 neighbors:  0.6666666666666666
Accuracy score with 6 neighbors:  0.6666666666666666
Accuracy score with 7 neighbors:  0.6666666666666666
Accuracy score with 8 neighbors:  0.6666666666666666
Accuracy score with 9 neighbors:  0.6666666666666666
Accuracy score with 10 neighbors:  0.6547619047619048